### ISSUE TITLE
Vorstellung des Projekts

### ISSUE THREAD

**Issue by damic103** [ProPra16/programmierpraktikum-abschlussprojekt-amigos#8]
Hallo zusammen,
im Rahmen der Korrektur würde ich gerne den aktuellen Stand eures Projektes diese Woche bei einem kurzen Treffen vorgestellt bekommen. Dabei sollte jeder seinen eigenen erbrachten Teil erklären können. Wann habt ihr Zeit? Ich bin diese Woche jeden Tag mittags in der Uni. Das Treffen sollte nicht länger als 15 Minuten dauern.

**Comment by jouhl101** [comment]
Hallo,

wir könnten uns Mittwoch 12:00 Uhr vorstellen, ginge das bei dir?

**Comment by damic103** [comment]
Ja das passt. Wir treffen uns am besten bei den gelben Tischen vor dem unteren Eingang von Hörsaal 5D.
